//
//  UsersModels.swift
//  GithubUsers
//
//  Created by Nik Cane on 07/09/16.
//  Copyright (c) 2016 Nik Cane. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct UsersRequest
{
  let startsWith: Int
  let completion: ([UserModel]?)->()
}

struct FollowersRequest
{
  let urlStr: String
  let completion: ([UserModel]?)->()
}
