//
//  MasterConfigurator.swift
//  GithubUsers
//
//  Created by Nik Cane on 07/09/16.
//  Copyright (c) 2016 Nik Cane. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

class MasterConfigurator
{
  // MARK: Configuration
  
  class func configure(viewController: MasterViewController, masterMode: Bool)
  {
    let presenter = MasterPresenter()
    presenter.output = viewController
    
    let interactor = MasterInteractor()
    interactor.output = presenter
    
    if masterMode {
      viewController.masterOutput = interactor
    }
    else {
      viewController.detailOutput = interactor
    }
  }
}
