//
//  MasterPresenter.swift
//  GithubUsers
//
//  Created by Nik Cane on 07/09/16.
//  Copyright (c) 2016 Nik Cane. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol MasterPresenterOutput: class
{
  func presentUsers()
}

class MasterPresenter
{
  weak var output: MasterPresenterOutput!
}

// MARK: Presentation logic

extension MasterPresenter: MasterInteractorOutput
{
  func prepareUsers()
  {
    dispatch_async(dispatch_get_main_queue(), { [weak self] in
      self?.output.presentUsers()
    })
  }
  
  func showUsersLoadAlert()
  {
    dispatch_async(dispatch_get_main_queue(), {
      UIAlertView(title: "Error", message: "Your request is not loaded correctly", delegate: nil, cancelButtonTitle: "Shit!!!")
        .show()
    })
  }
}
